# Create a pod called time-check in the devops namespace. The pod should contain a container named time-check
# utilizing the busybox image with the latest tag (specify as busybox:latest).

# Create a config map named time-config with the data TIME_FREQ=7 in the same namespace.

# Configure the time-check container to execute the command: while true; do date; sleep $TIME_FREQ;done. Ensure the 
# result is written /opt/itadmin/time/time-check.log. Also, add an environmental variable TIME_FREQ in the container, 
# fetching its value from the config map TIME_FREQ key.
# Create a volume log-volume and mount it at /opt/itadmin/time within the container.


apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: devops
spec:
  containers:
    - name: time-check
      image: busybox:latest
      command: ["/bin/sh", "-c", "while true; do date >> /opt/itadmin/time/time-check.log; sleep $TIME_FREQ; done"]

      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              key: TIME_FREQ
              name: time-config
      volumeMounts:
        - mountPath: /opt/itadmin/time
          name: log-volume

  volumes:
    - name: log-volume
      #emptyDir: {} #This is an ephemeral type of storage starts empty and exists as long as deployment resource is running 
      # (useful for caching, intermediate data,or logs) No size Limits
      emptyDir:
        sizeLimit: "1Gi" # 1gb size limit
      
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: devops
data:
  TIME_FREQ: "7"


---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicationcontroller
  labels:
    app: nginx_app
    type: front-end
spec:
  replicas: 3
  selector:
    app: nginx_app
  template:
    metadata:
      labels:
          app: nginx_app
          type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest