apiVersion: batch/v1
kind: CronJob
metadata:
  name: datacenter
spec:
  schedule: "*/11 * * * *" #sets job to run every 11 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-datacenter
              image: nginx:latest
              command: ["/bin/sh", "-c", "echo 'lllll"] #this commands runs inside the container and output the message 
          restartPolicy: OnFailure # pod is restarted only if it fails 


# * * * * *
# | | | | |
# | | | | └── Day of the week (0 - 7) (Sunday to Saturday, 0 and 7 both represent Sunday)
# | | | └──── Month (1 - 12)
# | | └────── Day of the month (1 - 31)
# | └──────── Hour (0 - 23)
# └────────── Minute (0 - 59)
