apiVersion: v1  #api version of the k8s api youre using to create the deployment

kind: Pod #kind of deployment youre creating

metadata: #metadata about the deployment
  name: ife-pod #name of the deployment
  labels: #key:value pair
    app: ife-pod #this is a label attached to the deployment (used for organizing and identifying resources )
    
spec: #describes the desired state of the deployment
  containers:
    - name: ife-pod
      image: xownsolutions/247travels.com:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "15Mi"
          cpu: "100m"
        limits:
          memory: "20Mi"
          cpu: "100m"

    