apiVersion: v1
kind: Service
metadata:
  name: ife-svc
  labels:
    app: ife-svc
    component: djdd
spec:
  type: LoadBalancer
  selector:
    app: ife
  ports:
    - port: 8080
      name: ife-svc